name = "Backend"
uuid = "10168745-524e-40de-81c0-a4ecaefcd244"
authors = ["AlonsoTheDopest <138828524+AlonsoTheDopest@users.noreply.github.com>"]
version = "0.1.0"

[deps]
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Genie = "c43c736e-a2d1-11e8-161f-af95117fbd1e"
Gmsh = "705231aa-382f-11e9-3f0c-b7cb4346fdeb"
Gridap = "56d4f2e9-7ea1-5844-9cf6-b9c51ca7ce8e"
GridapGmsh = "3025c34a-b394-11e9-2a55-3fee550c04c8"
GridapMakie = "41f30b06-6382-4b60-a5f7-79d86b35bf5d"
Inflector = "6d011eab-0732-4556-8808-e463c76bf3b6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
NLopt = "76087f3c-5699-56af-9a33-bf431cd00edd"
SearchLight = "340e8cb6-72eb-11e8-37ce-c97ebeb32050"
SearchLightPostgreSQL = "4327cdd6-4902-11ea-0272-430cea0431bd"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
Base64 = "1.11.0"
CairoMakie = "0.15.8"
ChainRulesCore = "1.26.0"
Dates = "1.11.0"
Genie = "5.35.6"
Gmsh = "0.3.1"
Gridap = "0.19.7"
GridapGmsh = "0.7.3"
GridapMakie = "0.1.7"
Inflector = "1.1.0"
LinearAlgebra = "1.11.0"
Logging = "1.11.0"
NLopt = "1.2.1"
SearchLight = "2.11.2"
SearchLightPostgreSQL = "2.4.0"
Zygote = "0.7.10"
